/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as WearablesRouteImport } from './routes/wearables'
import { Route as TrainersRouteImport } from './routes/trainers'
import { Route as TelehealthRouteImport } from './routes/telehealth'
import { Route as SleepHealthRouteImport } from './routes/sleep-health'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as MentalWellnessRouteImport } from './routes/mental-wellness'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HealthHistoryRouteImport } from './routes/health-history'
import { Route as DotRemindersRouteImport } from './routes/dot-reminders'
import { Route as DotPrepRouteImport } from './routes/dot-prep'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsIdRouteImport } from './routes/workouts.$id'
import { Route as MentalWellnessWindDownRouteImport } from './routes/mental-wellness.wind-down'
import { Route as MentalWellnessStressCheckRouteImport } from './routes/mental-wellness.stress-check'
import { Route as MentalWellnessSoundsRouteImport } from './routes/mental-wellness.sounds'
import { Route as MentalWellnessQuickResetRouteImport } from './routes/mental-wellness.quick-reset'
import { Route as MentalWellnessMoodRouteImport } from './routes/mental-wellness.mood'
import { Route as MentalWellnessJournalRouteImport } from './routes/mental-wellness.journal'
import { Route as MentalWellnessBreathingRouteImport } from './routes/mental-wellness.breathing'

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const WearablesRoute = WearablesRouteImport.update({
  id: '/wearables',
  path: '/wearables',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersRoute = TrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => rootRouteImport,
} as any)
const TelehealthRoute = TelehealthRouteImport.update({
  id: '/telehealth',
  path: '/telehealth',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepHealthRoute = SleepHealthRouteImport.update({
  id: '/sleep-health',
  path: '/sleep-health',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MentalWellnessRoute = MentalWellnessRouteImport.update({
  id: '/mental-wellness',
  path: '/mental-wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthHistoryRoute = HealthHistoryRouteImport.update({
  id: '/health-history',
  path: '/health-history',
  getParentRoute: () => rootRouteImport,
} as any)
const DotRemindersRoute = DotRemindersRouteImport.update({
  id: '/dot-reminders',
  path: '/dot-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const DotPrepRoute = DotPrepRouteImport.update({
  id: '/dot-prep',
  path: '/dot-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIdRoute = WorkoutsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkoutsRoute,
} as any)
const MentalWellnessWindDownRoute = MentalWellnessWindDownRouteImport.update({
  id: '/wind-down',
  path: '/wind-down',
  getParentRoute: () => MentalWellnessRoute,
} as any)
const MentalWellnessStressCheckRoute =
  MentalWellnessStressCheckRouteImport.update({
    id: '/stress-check',
    path: '/stress-check',
    getParentRoute: () => MentalWellnessRoute,
  } as any)
const MentalWellnessSoundsRoute = MentalWellnessSoundsRouteImport.update({
  id: '/sounds',
  path: '/sounds',
  getParentRoute: () => MentalWellnessRoute,
} as any)
const MentalWellnessQuickResetRoute =
  MentalWellnessQuickResetRouteImport.update({
    id: '/quick-reset',
    path: '/quick-reset',
    getParentRoute: () => MentalWellnessRoute,
  } as any)
const MentalWellnessMoodRoute = MentalWellnessMoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => MentalWellnessRoute,
} as any)
const MentalWellnessJournalRoute = MentalWellnessJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => MentalWellnessRoute,
} as any)
const MentalWellnessBreathingRoute = MentalWellnessBreathingRouteImport.update({
  id: '/breathing',
  path: '/breathing',
  getParentRoute: () => MentalWellnessRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/checkin': typeof CheckinRoute
  '/dashboard': typeof DashboardRoute
  '/dot-prep': typeof DotPrepRoute
  '/dot-reminders': typeof DotRemindersRoute
  '/health-history': typeof HealthHistoryRoute
  '/help': typeof HelpRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/mental-wellness': typeof MentalWellnessRouteWithChildren
  '/menu': typeof MenuRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sleep-health': typeof SleepHealthRoute
  '/telehealth': typeof TelehealthRoute
  '/trainers': typeof TrainersRoute
  '/wearables': typeof WearablesRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/mental-wellness/breathing': typeof MentalWellnessBreathingRoute
  '/mental-wellness/journal': typeof MentalWellnessJournalRoute
  '/mental-wellness/mood': typeof MentalWellnessMoodRoute
  '/mental-wellness/quick-reset': typeof MentalWellnessQuickResetRoute
  '/mental-wellness/sounds': typeof MentalWellnessSoundsRoute
  '/mental-wellness/stress-check': typeof MentalWellnessStressCheckRoute
  '/mental-wellness/wind-down': typeof MentalWellnessWindDownRoute
  '/workouts/$id': typeof WorkoutsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/checkin': typeof CheckinRoute
  '/dashboard': typeof DashboardRoute
  '/dot-prep': typeof DotPrepRoute
  '/dot-reminders': typeof DotRemindersRoute
  '/health-history': typeof HealthHistoryRoute
  '/help': typeof HelpRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/mental-wellness': typeof MentalWellnessRouteWithChildren
  '/menu': typeof MenuRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sleep-health': typeof SleepHealthRoute
  '/telehealth': typeof TelehealthRoute
  '/trainers': typeof TrainersRoute
  '/wearables': typeof WearablesRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/mental-wellness/breathing': typeof MentalWellnessBreathingRoute
  '/mental-wellness/journal': typeof MentalWellnessJournalRoute
  '/mental-wellness/mood': typeof MentalWellnessMoodRoute
  '/mental-wellness/quick-reset': typeof MentalWellnessQuickResetRoute
  '/mental-wellness/sounds': typeof MentalWellnessSoundsRoute
  '/mental-wellness/stress-check': typeof MentalWellnessStressCheckRoute
  '/mental-wellness/wind-down': typeof MentalWellnessWindDownRoute
  '/workouts/$id': typeof WorkoutsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/checkin': typeof CheckinRoute
  '/dashboard': typeof DashboardRoute
  '/dot-prep': typeof DotPrepRoute
  '/dot-reminders': typeof DotRemindersRoute
  '/health-history': typeof HealthHistoryRoute
  '/help': typeof HelpRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/mental-wellness': typeof MentalWellnessRouteWithChildren
  '/menu': typeof MenuRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sleep-health': typeof SleepHealthRoute
  '/telehealth': typeof TelehealthRoute
  '/trainers': typeof TrainersRoute
  '/wearables': typeof WearablesRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/mental-wellness/breathing': typeof MentalWellnessBreathingRoute
  '/mental-wellness/journal': typeof MentalWellnessJournalRoute
  '/mental-wellness/mood': typeof MentalWellnessMoodRoute
  '/mental-wellness/quick-reset': typeof MentalWellnessQuickResetRoute
  '/mental-wellness/sounds': typeof MentalWellnessSoundsRoute
  '/mental-wellness/stress-check': typeof MentalWellnessStressCheckRoute
  '/mental-wellness/wind-down': typeof MentalWellnessWindDownRoute
  '/workouts/$id': typeof WorkoutsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/checkin'
    | '/dashboard'
    | '/dot-prep'
    | '/dot-reminders'
    | '/health-history'
    | '/help'
    | '/locations'
    | '/login'
    | '/mental-wellness'
    | '/menu'
    | '/nutrition'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/register'
    | '/settings'
    | '/sleep-health'
    | '/telehealth'
    | '/trainers'
    | '/wearables'
    | '/workouts'
    | '/mental-wellness/breathing'
    | '/mental-wellness/journal'
    | '/mental-wellness/mood'
    | '/mental-wellness/quick-reset'
    | '/mental-wellness/sounds'
    | '/mental-wellness/stress-check'
    | '/mental-wellness/wind-down'
    | '/workouts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/checkin'
    | '/dashboard'
    | '/dot-prep'
    | '/dot-reminders'
    | '/health-history'
    | '/help'
    | '/locations'
    | '/login'
    | '/mental-wellness'
    | '/menu'
    | '/nutrition'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/register'
    | '/settings'
    | '/sleep-health'
    | '/telehealth'
    | '/trainers'
    | '/wearables'
    | '/workouts'
    | '/mental-wellness/breathing'
    | '/mental-wellness/journal'
    | '/mental-wellness/mood'
    | '/mental-wellness/quick-reset'
    | '/mental-wellness/sounds'
    | '/mental-wellness/stress-check'
    | '/mental-wellness/wind-down'
    | '/workouts/$id'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/checkin'
    | '/dashboard'
    | '/dot-prep'
    | '/dot-reminders'
    | '/health-history'
    | '/help'
    | '/locations'
    | '/login'
    | '/mental-wellness'
    | '/menu'
    | '/nutrition'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/register'
    | '/settings'
    | '/sleep-health'
    | '/telehealth'
    | '/trainers'
    | '/wearables'
    | '/workouts'
    | '/mental-wellness/breathing'
    | '/mental-wellness/journal'
    | '/mental-wellness/mood'
    | '/mental-wellness/quick-reset'
    | '/mental-wellness/sounds'
    | '/mental-wellness/stress-check'
    | '/mental-wellness/wind-down'
    | '/workouts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  CheckinRoute: typeof CheckinRoute
  DashboardRoute: typeof DashboardRoute
  DotPrepRoute: typeof DotPrepRoute
  DotRemindersRoute: typeof DotRemindersRoute
  HealthHistoryRoute: typeof HealthHistoryRoute
  HelpRoute: typeof HelpRoute
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  MentalWellnessRoute: typeof MentalWellnessRouteWithChildren
  MenuRoute: typeof MenuRoute
  NutritionRoute: typeof NutritionRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  SleepHealthRoute: typeof SleepHealthRoute
  TelehealthRoute: typeof TelehealthRoute
  TrainersRoute: typeof TrainersRoute
  WearablesRoute: typeof WearablesRoute
  WorkoutsRoute: typeof WorkoutsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wearables': {
      id: '/wearables'
      path: '/wearables'
      fullPath: '/wearables'
      preLoaderRoute: typeof WearablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers': {
      id: '/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof TrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telehealth': {
      id: '/telehealth'
      path: '/telehealth'
      fullPath: '/telehealth'
      preLoaderRoute: typeof TelehealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep-health': {
      id: '/sleep-health'
      path: '/sleep-health'
      fullPath: '/sleep-health'
      preLoaderRoute: typeof SleepHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mental-wellness': {
      id: '/mental-wellness'
      path: '/mental-wellness'
      fullPath: '/mental-wellness'
      preLoaderRoute: typeof MentalWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-history': {
      id: '/health-history'
      path: '/health-history'
      fullPath: '/health-history'
      preLoaderRoute: typeof HealthHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dot-reminders': {
      id: '/dot-reminders'
      path: '/dot-reminders'
      fullPath: '/dot-reminders'
      preLoaderRoute: typeof DotRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dot-prep': {
      id: '/dot-prep'
      path: '/dot-prep'
      fullPath: '/dot-prep'
      preLoaderRoute: typeof DotPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/$id': {
      id: '/workouts/$id'
      path: '/$id'
      fullPath: '/workouts/$id'
      preLoaderRoute: typeof WorkoutsIdRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/mental-wellness/wind-down': {
      id: '/mental-wellness/wind-down'
      path: '/wind-down'
      fullPath: '/mental-wellness/wind-down'
      preLoaderRoute: typeof MentalWellnessWindDownRouteImport
      parentRoute: typeof MentalWellnessRoute
    }
    '/mental-wellness/stress-check': {
      id: '/mental-wellness/stress-check'
      path: '/stress-check'
      fullPath: '/mental-wellness/stress-check'
      preLoaderRoute: typeof MentalWellnessStressCheckRouteImport
      parentRoute: typeof MentalWellnessRoute
    }
    '/mental-wellness/sounds': {
      id: '/mental-wellness/sounds'
      path: '/sounds'
      fullPath: '/mental-wellness/sounds'
      preLoaderRoute: typeof MentalWellnessSoundsRouteImport
      parentRoute: typeof MentalWellnessRoute
    }
    '/mental-wellness/quick-reset': {
      id: '/mental-wellness/quick-reset'
      path: '/quick-reset'
      fullPath: '/mental-wellness/quick-reset'
      preLoaderRoute: typeof MentalWellnessQuickResetRouteImport
      parentRoute: typeof MentalWellnessRoute
    }
    '/mental-wellness/mood': {
      id: '/mental-wellness/mood'
      path: '/mood'
      fullPath: '/mental-wellness/mood'
      preLoaderRoute: typeof MentalWellnessMoodRouteImport
      parentRoute: typeof MentalWellnessRoute
    }
    '/mental-wellness/journal': {
      id: '/mental-wellness/journal'
      path: '/journal'
      fullPath: '/mental-wellness/journal'
      preLoaderRoute: typeof MentalWellnessJournalRouteImport
      parentRoute: typeof MentalWellnessRoute
    }
    '/mental-wellness/breathing': {
      id: '/mental-wellness/breathing'
      path: '/breathing'
      fullPath: '/mental-wellness/breathing'
      preLoaderRoute: typeof MentalWellnessBreathingRouteImport
      parentRoute: typeof MentalWellnessRoute
    }
  }
}

interface MentalWellnessRouteChildren {
  MentalWellnessBreathingRoute: typeof MentalWellnessBreathingRoute
  MentalWellnessJournalRoute: typeof MentalWellnessJournalRoute
  MentalWellnessMoodRoute: typeof MentalWellnessMoodRoute
  MentalWellnessQuickResetRoute: typeof MentalWellnessQuickResetRoute
  MentalWellnessSoundsRoute: typeof MentalWellnessSoundsRoute
  MentalWellnessStressCheckRoute: typeof MentalWellnessStressCheckRoute
  MentalWellnessWindDownRoute: typeof MentalWellnessWindDownRoute
}

const MentalWellnessRouteChildren: MentalWellnessRouteChildren = {
  MentalWellnessBreathingRoute: MentalWellnessBreathingRoute,
  MentalWellnessJournalRoute: MentalWellnessJournalRoute,
  MentalWellnessMoodRoute: MentalWellnessMoodRoute,
  MentalWellnessQuickResetRoute: MentalWellnessQuickResetRoute,
  MentalWellnessSoundsRoute: MentalWellnessSoundsRoute,
  MentalWellnessStressCheckRoute: MentalWellnessStressCheckRoute,
  MentalWellnessWindDownRoute: MentalWellnessWindDownRoute,
}

const MentalWellnessRouteWithChildren = MentalWellnessRoute._addFileChildren(
  MentalWellnessRouteChildren,
)

interface WorkoutsRouteChildren {
  WorkoutsIdRoute: typeof WorkoutsIdRoute
}

const WorkoutsRouteChildren: WorkoutsRouteChildren = {
  WorkoutsIdRoute: WorkoutsIdRoute,
}

const WorkoutsRouteWithChildren = WorkoutsRoute._addFileChildren(
  WorkoutsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  CheckinRoute: CheckinRoute,
  DashboardRoute: DashboardRoute,
  DotPrepRoute: DotPrepRoute,
  DotRemindersRoute: DotRemindersRoute,
  HealthHistoryRoute: HealthHistoryRoute,
  HelpRoute: HelpRoute,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  MentalWellnessRoute: MentalWellnessRouteWithChildren,
  MenuRoute: MenuRoute,
  NutritionRoute: NutritionRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  SleepHealthRoute: SleepHealthRoute,
  TelehealthRoute: TelehealthRoute,
  TrainersRoute: TrainersRoute,
  WearablesRoute: WearablesRoute,
  WorkoutsRoute: WorkoutsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
